### PR TITLE
Tests to CI

### PR DESCRIPTION
**Pull request by MCJOHN974**
Here I add calling some functions of compiled contracts and checking correctness of answer and return code into CI. It is still not very generic but better than nothing

### CODE REVIEW

**Comment by MCJOHN974** [comment]
I added self-hosted runner and now it works without downloading something and with running some tests of compiled contracts.

Now I run my self-hosted runner in my laptop. 
How I configure my runner:
  1) execute all scripts from github tutorial
  2) go to actions-runner directory and manually install all prerequirements (solc, wasmtime, etc)
  3) just start my runner and it can run jobs without installing anything in job.
  
Before I will ask an ssh-key of some aurora machine to move this runner from my laptop, @birchmd is it a way people usually configure self-hosted github runners. Especially second step

**Comment by MCJOHN974** [comment]
Finally, it works (: It is not very good and generic but it definitely more strict that previous CI. Added unit tests, linters to CI. Also in this version of CI some compiled contracts are runned and their stdouts and returncodes are checked.

@birchmd WDYT about merging it in  MCJOHN974/master (it will appear in our PR to aurora-is-near/evm2near) ?

Also, @vzctl thanks for help with wasmtime installation!

**Review by birchmd — APPROVED** [review]
Nice, thanks for this @MCJOHN974 

Do you we still want it to run on a self-hosted runner or are we ok with `runs-on: ubuntu-latest`?

Yes, you can merge it into the master branch of your fork. Getting these changes in upstream as part of the open PR is good with me.

**Comment by MCJOHN974** [comment]
> Do you we still want it to run on a self-hosted runner or are we ok with `runs-on: ubuntu-latest`?

It maybe will provide better execution time of CI job by caching, I think I will work on it after big PR to aurora repo will merged

**Pull request merged**
